name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    # uses: ./.github/workflows/build-test.yml
    uses: ./.github/workflows/build-docker.yml
    with:
      build_type: 'Release'
      update_version: false
      with_coverage: true